steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/preceptor-feedback-bot:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/preceptor-feedback-bot:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  # NOTE: Secrets (OAUTH_CLIENT_ID, OAUTH_CLIENT_SECRET, JWT_SECRET_KEY) are managed
  # via Google Secret Manager and injected using --set-secrets flag below
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'preceptor-feedback-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/preceptor-feedback-bot:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--timeout'
      - '600'
      - '--set-env-vars'
      - 'DEPLOYMENT_ENV=cloud,GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=us-central1,MODEL_NAME=gemini-2.5-flash,LOG_BUCKET=meded-feedback-bot-logs,CLOUD_RUN_TIMEOUT=600,OAUTH_DOMAIN_RESTRICTION=true,OAUTH_ALLOWED_DOMAINS=case.edu,FIRESTORE_DATABASE=(default),DEBUG=false,OAUTH_REDIRECT_URI=https://preceptor-feedback-bot-hki4fdufla-uc.a.run.app/auth/callback'
      - '--set-secrets'
      - 'JWT_SECRET_KEY=preceptor-bot-jwt-secret:latest,OAUTH_CLIENT_ID=preceptor-bot-oauth-client-id:latest,OAUTH_CLIENT_SECRET=preceptor-bot-oauth-client-secret:latest'

images:
  - 'gcr.io/$PROJECT_ID/preceptor-feedback-bot:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY