steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/preceptor-feedback-bot:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/preceptor-feedback-bot:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'preceptor-feedback-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/preceptor-feedback-bot:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--timeout'
      - '600'
      - '--set-env-vars'
      - 'DEPLOYMENT_ENV=cloud,GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=us-central1,MODEL_NAME=gemini-2.0-flash-001,LOG_BUCKET=meded-feedback-bot-logs,CLOUD_RUN_TIMEOUT=600'

images:
  - 'gcr.io/$PROJECT_ID/preceptor-feedback-bot:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY